# Generated by Django 5.0.4 on 2024-04-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.CharField(max_length=250, primary_key=True, serialize=False)),
            ],
        ),
    ]
