# Generated by Django 5.0.4 on 2024-05-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
