# Generated by Django 5.0.4 on 2024-05-02 07:19

import django.db.models.deletion
import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HFRoutingApp', '0002_delete_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('customer_id', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SalesWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=6, unique=True)),
                ('start_dow', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('location_id', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='geolocation')),
                ('customer', models.ForeignKey(default=None, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.customer', verbose_name='customer')),
            ],
        ),
    ]
