# Generated by Django 5.0.4 on 2024-05-02 11:20

import django.db.models.deletion
import django_google_maps.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FillDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='LocationGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='postal code')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='geolocation')),
                ('max_vehicle_load', models.IntegerField()),
                ('starting_time', models.TimeField()),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OperatorLocationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Weekday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (0, 'Sunday')])),
                ('available', models.CharField(choices=[('yes', 'Yes'), ('no', 'No')], max_length=3)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesWindow',
        ),
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='filldate',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.location'),
        ),
        migrations.AddField(
            model_name='locationgroup',
            name='locations',
            field=models.ManyToManyField(to='HFRoutingApp.location'),
        ),
        migrations.AddField(
            model_name='operatorlocationlink',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.location'),
        ),
        migrations.AddField(
            model_name='operatorlocationlink',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.operator'),
        ),
        migrations.AddField(
            model_name='operator',
            name='availability',
            field=models.ManyToManyField(blank=True, to='HFRoutingApp.weekday'),
        ),
    ]
