# Generated by Django 5.0.4 on 2024-05-02 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0004_filldate_locationgroup_operator_operatorlocationlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='fill_dates',
            field=models.ManyToManyField(blank=True, to='HFRoutingApp.weekday'),
        ),
        migrations.DeleteModel(
            name='FillDate',
        ),
    ]
