# Generated by Django 5.0.4 on 2024-05-02 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0005_location_fill_dates_delete_filldate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weekday',
            name='available',
        ),
    ]
