# Generated by Django 5.0.4 on 2024-05-02 13:42

import django.db.models.deletion
import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0006_remove_weekday_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='geolocation')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('machine_id', models.IntegerField(blank=True, default=None, null=True)),
                ('brand', models.CharField(max_length=80)),
                ('manufacturer_serialnumber', models.CharField(max_length=80)),
                ('hostname', models.CharField(max_length=80)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_id', models.SmallIntegerField()),
                ('honesty_model', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='location',
            name='removal_probability',
            field=models.FloatField(blank=True, null=True, verbose_name='removal probability'),
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_catering', models.BooleanField(default=False)),
                ('activation_date', models.DateField()),
                ('pricelist_id', models.IntegerField(blank=True, default=None, null=True)),
                ('resembles_id', models.IntegerField(blank=True, default=None, null=True)),
                ('product_filter', models.IntegerField(blank=True, default=None, null=True)),
                ('pilot', models.BooleanField(default=False)),
                ('spot_hours', models.IntegerField(default=0)),
                ('location', models.ForeignKey(default=None, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.location')),
                ('machine', models.ForeignKey(default=None, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.machine')),
            ],
        ),
    ]
