# Generated by Django 5.0.4 on 2024-05-02 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0007_cateringorder_hub_machine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringorder',
            name='spot',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.spot'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='hostname',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
