# Generated by Django 5.0.4 on 2024-05-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0008_cateringorder_spot_alter_machine_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
