# Generated by Django 5.0.4 on 2024-05-07 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0009_operator_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.CharField(max_length=1000)),
                ('day', models.DateField()),
                ('locations', models.ManyToManyField(to='HFRoutingApp.location')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.operator')),
            ],
        ),
    ]
