# Generated by Django 5.0.4 on 2024-05-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0010_routes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Routes',
            new_name='Route',
        ),
    ]
