# Generated by Django 5.0.4 on 2024-05-08 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0013_location_opening_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='fill_time_minutes',
        ),
        migrations.AddField(
            model_name='route',
            name='hub',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.hub'),
        ),
        migrations.AddField(
            model_name='spot',
            name='fill_time_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='spot',
            name='walking_time_minutes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
