# Generated by Django 5.0.4 on 2024-05-08 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0015_remove_location_fill_dates_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocationGroup',
        ),
    ]
