# Generated by Django 5.0.4 on 2024-05-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0020_cateringorderline_picklistline'),
    ]

    operations = [
        migrations.AddField(
            model_name='spot',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
    ]
