# Generated by Django 5.0.4 on 2024-05-16 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0021_spot_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='postal_code',
        ),
        migrations.AlterField(
            model_name='operator',
            name='address',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='address'),
        ),
    ]
