# Generated by Django 5.0.4 on 2024-05-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0023_distancematrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location_id',
        ),
    ]
