# Generated by Django 5.0.4 on 2024-05-16 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0024_remove_location_location_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='customer_id',
        ),
    ]
