# Generated by Django 5.0.4 on 2024-05-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0025_remove_customer_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hub',
            name='active',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='address',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='geolocation',
        ),
        migrations.AddField(
            model_name='hub',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.location'),
        ),
    ]
