# Generated by Django 5.0.4 on 2024-05-16 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0026_remove_hub_active_remove_hub_address_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='distancematrix',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='HFRoutingApp.location'),
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='distance_meters',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='origin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='HFRoutingApp.location'),
        ),
        migrations.RemoveField(
            model_name='distancematrix',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='distancematrix',
            name='from_location',
        ),
        migrations.RemoveField(
            model_name='distancematrix',
            name='to_location',
        ),
    ]
