# Generated by Django 5.0.4 on 2024-05-21 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0027_alter_distancematrix_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='location',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.location'),
        ),
    ]
