# Generated by Django 5.0.4 on 2024-05-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0028_operator_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='address',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='geolocation',
        ),
    ]
