# Generated by Django 5.0.4 on 2024-06-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0030_operatorplanning'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='availability',
        ),
        migrations.AddField(
            model_name='route',
            name='is_base_route',
            field=models.BooleanField(default=False),
        ),
    ]
