# Generated by Django 5.0.4 on 2024-06-18 08:11

import django.db.models.deletion
import django_google_maps.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0031_remove_operator_availability_route_is_base_route'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geo',
            fields=[
                ('geo_id', models.AutoField(primary_key=True, serialize=False)),
                ('address', django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='address')),
                ('geolocation', django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='geolocation')),
            ],
        ),
        migrations.RemoveField(
            model_name='location',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='hub',
            name='location',
        ),
        migrations.RemoveField(
            model_name='operator',
            name='location',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='location',
        ),
        migrations.RemoveField(
            model_name='route',
            name='locations',
        ),
        migrations.RemoveField(
            model_name='operatorlocationlink',
            name='location',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='machine',
        ),
        migrations.RemoveField(
            model_name='operatorlocationlink',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='activation_date',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='pricelist_id',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='product_filter',
        ),
        migrations.RemoveField(
            model_name='spot',
            name='resembles_id',
        ),
        migrations.AddField(
            model_name='hub',
            name='geo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.geo'),
        ),
        migrations.AddField(
            model_name='operator',
            name='geo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.geo'),
        ),
        migrations.AddField(
            model_name='route',
            name='geos',
            field=models.ManyToManyField(to='HFRoutingApp.geo'),
        ),
        migrations.AddField(
            model_name='spot',
            name='geo',
            field=models.ForeignKey(default=None, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.geo'),
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='destination',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='distances_to', to='HFRoutingApp.geo'),
        ),
        migrations.AlterField(
            model_name='distancematrix',
            name='origin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='distances_from', to='HFRoutingApp.geo'),
        ),
        migrations.CreateModel(
            name='OperatorGeoLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.geo')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HFRoutingApp.operator')),
            ],
        ),
        migrations.DeleteModel(
            name='Machine',
        ),
        migrations.DeleteModel(
            name='OperatorLocationLink',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
