# Generated by Django 5.0.4 on 2024-06-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0032_geo_remove_location_customer_remove_hub_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
