# Generated by Django 5.0.4 on 2024-06-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0033_hub_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortcode', models.CharField(max_length=7)),
                ('description', models.CharField(max_length=80)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('opening_time', models.TimeField(blank=True, null=True, verbose_name='opening time')),
                ('customer', models.ForeignKey(default=None, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.customer', verbose_name='customer')),
                ('geo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.geo')),
            ],
        ),
    ]
