# Generated by Django 5.0.4 on 2024-06-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0034_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spot',
            name='geo',
        ),
        migrations.AddField(
            model_name='spot',
            name='location',
            field=models.ForeignKey(default=None, limit_choices_to={'active': True}, on_delete=django.db.models.deletion.PROTECT, to='HFRoutingApp.location'),
        ),
    ]
