# Generated by Django 5.0.4 on 2024-06-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HFRoutingApp', '0035_remove_spot_geo_spot_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distancematrix',
            name='distance_meters',
            field=models.FloatField(null=True),
        ),
    ]
